user_pref('dom.ipc.processCount', 1)
user_pref('dom.ipc.processCount.webIsolated', 1)
user_pref('datareporting.healthreport.uploadEnabled', false)
user_pref('datareporting.policy.dataSubmissionEnabled', false)
user_pref('toolkit.telemetry.enabled', false)
user_pref('browser.shell.skipDefaultBrowserCheckOnFirstRun', true)
